### ISSUE TITLE
Applet error

### ISSUE THREAD

**Issue by G4Zz0L1** [cardsurf/download-and-upload-speed#9]
I'm on Arch, with cinnamon version 3.8.1-1

If you need other info to debug, feel free to ask

[download-and-upload-speed@cardsurf]: assignment to undeclared variable last_char
[download-and-upload-speed@cardsurf]: Failed to evaluate 'main' function on applet: download-and-upload-speed@cardsurf/83

**Comment by cardsurf** [comment]
Thanks for the info. I have pushed the changes to the master branch of this repository. You can download it from [here](https://github.com/cardsurf/download-and-upload-speed/archive/master.zip). Please let me know it works now.

**Comment by MichaelAkhnoukh** [comment]
i have the same setup as G4Zz0L1 and still getting an error
here is a log from looking glass

> error t=2018-05-07T00:59:25Z 
[download-and-upload-speed@cardsurf]: assignment to undeclared variable attribute_name
[download-and-upload-speed@cardsurf]: Failed to evaluate 'main' function on applet: download-and-upload-speed@cardsurf/24
trace t=2018-05-07T00:59:25Z 
<----------------
anonymous/CssStyle.prototype.add_or_modify_from_list@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/cssStylization.js:22:13
anonymous/CssStyle.prototype.add_or_modify_from_string@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/cssStylization.js:16:9
anonymous/CssConverter.prototype.convert_to_object@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/cssStylization.js:74:9
anonymous/CssStringStyler.prototype.get_numeric_value_or_null@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/cssStylization.js:119:26
anonymous/GuiSpeed.prototype.add_font_size@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/appletGui.js:162:25
anonymous/GuiSpeed.prototype.set_text_style@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/appletGui.js:153:21
anonymous/MyApplet.prototype.on_gui_css_changed@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:308:9
anonymous/MyApplet.prototype._add_gui_speed@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:595:9
anonymous/MyApplet.prototype._init_gui@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:587:9
anonymous/MyApplet.prototype._init@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:130:9
MyApplet@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:42:5
main@/home/abyss/.local/share/cinnamon/applets/download-and-upload-speed@cardsurf/applet.js:997:20
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:573:18
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:347:22
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:290:9

**Comment by cardsurf** [comment]
Thanks for the feedback. I have pushed the fix for the above issue as well. Please try it now.

**Comment by MichaelAkhnoukh** [comment]
thank you for rapid response, i can confirm that it is now working without any errors. however there is a warning that this applet contains function calls that can potentially cause cinnamon to crash.

**Comment by G4Zz0L1** [comment]
I think I've made something wrong, because after replacing all the files and reloading source, and restarting cinnamon, I still see a similar error:

[download-and-upload-speed@cardsurf]: Applet download-and-upload-speed@cardsurf: Could not create applet object.
[download-and-upload-speed@cardsurf]: Error importing applet.js from download-and-upload-speed@cardsurf

**Comment by cardsurf** [comment]
@MichaelAkhnoukh
Nice to hear that. The warning is displayed because in the past some applets made Cinnamon unstable. It encourages users to firstly check if one of the enabled applets is a culprit of poor system performance.

@G4Zz0L1:
Try to unistall the applet from the Cinnamon settings, copy applet files to ~/.local/share/cinnamon/applets/download-and-upload-speed/ and then enable it. If it still does not work please paste the log from `~/.cinnamon/glass.log.`

**Comment by MichaelAkhnoukh** [comment]
so far so good now on cinnamon 3.8.2 without any issues

**Comment by G4Zz0L1** [comment]
Perfect, it's working fine now. Thanks a lot and sorry for the delay!
